//! Memory-related functions and objects.

const builtin = @import("builtin");
const std = @import("std");
const math = std.math;
const heap = std.heap;
const mem = std.mem;
const Alignment = mem.Alignment;
const testing = std.testing;
const assert = std.debug.assert;
const Allocator = mem.Allocator;

// These functions are all when appending to the free list (it should have
// already resized itself)
fn null_alloc(ctx: *anyopaque, n: usize, alignment: mem.Alignment, ra: usize) ?[*]u8 {
    _ = ctx;
    _ = n;
    _ = alignment;
    _ = ra;
    return null;
}
fn null_resize(ctx: *anyopaque, buf: []u8, alignment: mem.Alignment, new_size: usize, return_address: usize) bool {
    _ = ctx;
    _ = buf;
    _ = alignment;
    _ = new_size;
    _ = return_address;
    return false;
}
fn null_remap(context: *anyopaque, memory: []u8, alignment: mem.Alignment, new_len: usize, return_address: usize) ?[*]u8 {
    _ = context;
    _ = memory;
    _ = alignment;
    _ = new_len;
    _ = return_address;
    return null;
}
fn null_free(ctx: *anyopaque, buf: []u8, alignment: mem.Alignment, return_address: usize) void {
    _ = ctx;
    _ = buf;
    _ = alignment;
    _ = return_address;
}
var null_ctx: usize = 0;
pub const null_allocator: Allocator = .{
    .ptr = &null_ctx,
    .vtable = &.{
        .alloc = null_alloc,
        .resize = null_resize,
        .remap = null_remap,
        .free = null_free,
    },
};

/// Note, this will hand out allocations that potentially alias. Really only useful for debugging.
pub const RingBufferAllocator = struct {
    buffer: []u8,
    end_index: usize,

    pub fn init(buffer: []u8) RingBufferAllocator {
        return .{
            .buffer = buffer,
            .end_index = 0,
        };
    }

    pub fn allocator(self: *RingBufferAllocator) Allocator {
        return .{
            .ptr = self,
            .vtable = &.{
                .alloc = alloc,
                .resize = resize,
                .remap = remap,
                .free = free,
            },
        };
    }

    fn calculateOffset(self: *RingBufferAllocator, n: usize, alignment: mem.Alignment) ?struct { alloc_at: [*]u8, new_end: usize } {
        const ptr_align = alignment.toByteUnits();
        const adjust_off = mem.alignPointerOffset(self.buffer.ptr + self.end_index, ptr_align) orelse return null;
        const adjusted_index = self.end_index + adjust_off;
        const new_end_index = adjusted_index + n;
        if (new_end_index > self.buffer.len) return null;

        return .{
            .alloc_at = self.buffer.ptr + adjusted_index,
            .new_end = new_end_index,
        };
    }

    pub fn alloc(ctx: *anyopaque, n: usize, alignment: mem.Alignment, ra: usize) ?[*]u8 {
        const self: *RingBufferAllocator = @ptrCast(@alignCast(ctx));
        _ = ra;

        if (self.calculateOffset(n, alignment)) |val| {
            self.end_index = val.new_end;
            return val.alloc_at;
        } else {
            // Wrap the buffer around.
            self.end_index = 0;
            if (self.calculateOffset(n, alignment)) |val| {
                self.end_index = val.new_end;
                return val.alloc_at;
            } else return null;
        }
    }

    pub fn resize(ctx: *anyopaque, buf: []u8, alignment: mem.Alignment, new_size: usize, return_address: usize) bool {
        _ = ctx;
        _ = buf;
        _ = alignment;
        _ = new_size;
        _ = return_address;
        return false;
    }

    pub fn remap(ctx: *anyopaque, memory: []u8, alignment: mem.Alignment, new_len: usize, return_address: usize) ?[*]u8 {
        _ = ctx;
        _ = memory;
        _ = alignment;
        _ = new_len;
        _ = return_address;
        return null;
    }

    pub fn free(ctx: *anyopaque, buf: []u8, alignment: mem.Alignment, return_address: usize) void {
        _ = ctx;
        _ = buf;
        _ = alignment;
        _ = return_address;
    }
};

/// Note: this code is largely generated by an LLM as I wanted to get things
/// working, this may need a refactor in the future.
///
/// Non-threadsafe, partially-rewindable bump allocator. Allocations come
/// from a singly linked list of chunks, appended in order. `current` tracks the
/// chunk currently being bumped into and `first` pins the oldest chunk so
/// the whole chain stays reachable for teardown. Individual `free` and
/// `resize` only touch the most recent allocation; everything else is
/// reclaimed in bulk by rewinding to a saved `Snapshot`.
///
/// Rewind never moves or frees nodes, it just moves `current` back. Chunks
/// appended after the snapshot stay linked after `current` and are overwritten in
/// place as later allocations walk forward into them, so a steady eval-frame
/// workload stops touching the child allocator after warmup.
///
/// Intended as the scratch allocator for eval-frame temporaries: take a
/// `snapshot` at frame entry, `rewind` to it at frame exit. Snapshots must be
/// rewound in LIFO order: rewinding to an older snapshot and then allocating
/// would overwrite nodes that newer snapshots still reference, which matches
/// the strict nesting of eval frames.
pub const RewindableArena = struct {
    child_allocator: Allocator,
    first: ?*Node = null,
    current: ?*Node = null,

    /// A point-in-time watermark. Save one with `snapshot` and restore it
    /// with `rewind`.
    pub const Snapshot = struct {
        /// `null` marks a snapshot taken before any chunk existed; rewinding
        /// to it resets the arena to fully empty.
        current: ?*Node,
        end_index: usize,
    };

    const Node = struct {
        /// Full allocation length, including the `Node` header.
        size: usize,
        /// Bytes consumed in this chunk's buffer.
        end_index: usize,
        next: ?*Node,

        fn buf(node: *Node) []u8 {
            return @as([*]u8, @ptrCast(node))[0..node.size][@sizeOf(Node)..];
        }

        fn allocatedSlice(node: *Node) []u8 {
            return @as([*]u8, @ptrCast(node))[0..node.size];
        }
    };

    pub fn init(child_allocator: Allocator) RewindableArena {
        return .{ .child_allocator = child_allocator };
    }

    pub fn deinit(arena: *RewindableArena) void {
        var it = arena.first;
        while (it) |node| {
            it = node.next;
            arena.child_allocator.rawFree(node.allocatedSlice(), .of(Node), @returnAddress());
        }
        arena.* = undefined;
    }

    pub fn allocator(self: *RewindableArena) Allocator {
        return .{
            .ptr = self,
            .vtable = &.{
                .alloc = alloc,
                .resize = resize,
                .remap = remap,
                .free = free,
            },
        };
    }

    /// Total bytes held across every chunk, excluding the `Node` headers.
    /// Stable across `rewind` since nodes are retained, not freed.
    pub fn queryCapacity(arena: *RewindableArena) usize {
        var capacity: usize = 0;
        var it = arena.first;
        while (it) |node| : (it = node.next) capacity += node.size - @sizeOf(Node);
        return capacity;
    }

    pub fn snapshot(arena: *RewindableArena) Snapshot {
        return .{
            .current = arena.current,
            .end_index = if (arena.current) |node| node.end_index else 0,
        };
    }

    /// Restore the arena to `snap`. Chunks linked after `snap`'s node stay
    /// in place and are overwritten as later allocations reach them.
    pub fn rewind(arena: *RewindableArena, snap: Snapshot) void {
        if (snap.current) |node| {
            arena.current = node;
            node.end_index = snap.end_index;
        } else {
            // A null snapshot predates any chunk, so reset to the start of
            // the chain and let future allocations reuse from `first`.
            arena.current = arena.first;
            if (arena.first) |node| node.end_index = 0;
        }
    }

    fn alignedIndex(buf_ptr: [*]u8, end_index: usize, alignment: Alignment) usize {
        // Wrapping arithmetic keeps this sound even though `end_index` is
        // not strictly bounded by `size` during the alignment computation.
        return alignment.forward(@intFromPtr(buf_ptr) +% end_index) -% @intFromPtr(buf_ptr);
    }

    fn alloc(ctx: *anyopaque, n: usize, alignment: Alignment, ra: usize) ?[*]u8 {
        const arena: *RewindableArena = @ptrCast(@alignCast(ctx));
        _ = ra;
        assert(n > 0);

        // Bump within the current chunk if it still has room.
        if (arena.current) |node| {
            const buf = node.buf();
            const aligned = alignedIndex(buf.ptr, node.end_index, alignment);
            if (aligned + n <= buf.len) {
                node.end_index = aligned + n;
                return buf[aligned..][0..n].ptr;
            }
        }

        // The current chunk is full or absent, so walk forward to the next
        // reusable chunk, the retained tail after `current` or `first` when
        // rewound to empty, and overwrite it from the start.
        const next_node: ?*Node = if (arena.current) |node| node.next else arena.first;
        if (next_node) |node| {
            const buf = node.buf();
            const aligned = alignedIndex(buf.ptr, 0, alignment);
            if (aligned + n <= buf.len) {
                node.end_index = aligned + n;
                arena.current = node;
                return buf[aligned..][0..n].ptr;
            }
        }

        // No retained chunk fits, so allocate a fresh one and splice it in
        // right after `current` (or as the new `first`), preserving any reusable
        // tail that follows. Geometric sizing amortizes future growth.
        const prev_buf_len: usize = if (arena.current) |node| node.buf().len else if (arena.first) |node| node.buf().len else 0;
        const min_size = @sizeOf(Node) + alignment.toByteUnits() + n;
        const big = prev_buf_len + min_size + 16;
        const size = mem.alignForward(usize, big + big / 2, 2);
        const ptr = arena.child_allocator.rawAlloc(size, .of(Node), @returnAddress()) orelse return null;
        const new_node: *Node = @ptrCast(@alignCast(ptr));
        new_node.size = size;
        new_node.next = if (arena.current) |node| node.next else arena.first;
        if (arena.current) |node| node.next = new_node else arena.first = new_node;
        arena.current = new_node;
        const buf = new_node.buf();
        const aligned = alignedIndex(buf.ptr, 0, alignment);
        new_node.end_index = aligned + n;
        return buf[aligned..][0..n].ptr;
    }

    fn resize(ctx: *anyopaque, memory: []u8, alignment: Alignment, new_len: usize, ra: usize) bool {
        const arena: *RewindableArena = @ptrCast(@alignCast(ctx));
        _ = alignment;
        _ = ra;
        assert(memory.len > 0);
        assert(new_len > 0);

        const node = arena.current orelse return false;
        const buf = node.buf();
        const current_end = node.end_index;

        // Only the most recent allocation, the tail of the current chunk, is
        // reachable for grow or shrink; anything else can only report a
        // no-op shrink, matching the std arena's contract.
        if (buf.ptr + current_end != memory.ptr + memory.len) return new_len <= memory.len;

        if (new_len <= memory.len) {
            node.end_index = current_end - (memory.len - new_len);
            return true;
        }
        if (buf.len -| current_end >= new_len - memory.len) {
            node.end_index = current_end + (new_len - memory.len);
            return true;
        }
        return false;
    }

    fn remap(ctx: *anyopaque, memory: []u8, alignment: Alignment, new_len: usize, ra: usize) ?[*]u8 {
        return if (resize(ctx, memory, alignment, new_len, ra)) memory.ptr else null;
    }

    fn free(ctx: *anyopaque, memory: []u8, alignment: Alignment, ra: usize) void {
        const arena: *RewindableArena = @ptrCast(@alignCast(ctx));
        _ = alignment;
        _ = ra;
        assert(memory.len > 0);

        const node = arena.current orelse return;
        if (node.buf().ptr + node.end_index != memory.ptr + memory.len) return;
        node.end_index -= memory.len;
    }
};

test "rewindable arena: rewind keeps chunks and reuses them" {
    var arena = RewindableArena.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // 65536 is large enough that a second allocation cannot fit in the first
    // chunk's slack, so each call forces a fresh chunk.
    _ = try a.alloc(u8, 65536);
    const snap = arena.snapshot();
    const cap_at_snap = arena.queryCapacity();
    _ = try a.alloc(u8, 65536);
    const cap_after_growth = arena.queryCapacity();
    try testing.expect(cap_after_growth > cap_at_snap);

    arena.rewind(snap);
    // The chunk appended after the snapshot is retained, not freed.
    try testing.expectEqual(cap_after_growth, arena.queryCapacity());

    // Re-allocating is served from the retained chunk, not a new one.
    _ = try a.alloc(u8, 65536);
    try testing.expectEqual(cap_after_growth, arena.queryCapacity());
}

test "rewindable arena: free reclaims only the most recent allocation" {
    var arena = RewindableArena.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const p1 = try a.alloc(u8, 8);
    const p2 = try a.alloc(u8, 8);
    // Freeing p2 (the tail) reclaims it; p1 is untouched.
    a.free(p2);
    const p3 = try a.alloc(u8, 8);
    try testing.expectEqual(@intFromPtr(p2.ptr), @intFromPtr(p3.ptr));

    // Freeing p1 is a no-op since p3 now sits above it.
    a.free(p1);
    const p4 = try a.alloc(u8, 8);
    try testing.expect(@intFromPtr(p4.ptr) > @intFromPtr(p1.ptr));
}

test "rewindable arena: resize grows and shrinks the tail in place" {
    var arena = RewindableArena.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const p = try a.alloc(u8, 16);
    // Grow within the chunk's slack; the tail moves past the grown region.
    try testing.expect(a.resize(p, 32));
    const q = try a.alloc(u8, 8);
    try testing.expectEqual(@intFromPtr(p.ptr) + 32, @intFromPtr(q.ptr));
    // p is no longer the tail, so growing it must fail.
    try testing.expect(!a.resize(p, 64));
}

test "rewindable arena: survives OOM mid-frame and rewinds cleanly" {
    const testRewindOom = struct {
        fn run(ta: Allocator) !void {
            var arena = RewindableArena.init(ta);
            defer arena.deinit();
            const a = arena.allocator();
            const snap = arena.snapshot();
            const p = try a.alloc(u8, 4096);
            @memset(p, 0);
            _ = try a.alloc(u8, 4096);
            arena.rewind(snap);
            _ = try a.alloc(u8, 2048);
        }
    }.run;
    try testing.checkAllAllocationFailures(testing.allocator, testRewindOom, .{});
}

test "rewindable arena: rewinding to an empty snapshot reuses the chain" {
    var arena = RewindableArena.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const snap = arena.snapshot();
    try testing.expect(snap.current == null);

    _ = try a.alloc(u8, 1024);
    _ = try a.alloc(u8, 1024);
    const cap = arena.queryCapacity();
    try testing.expect(cap > 0);

    // Rewinding to the pre-allocation snapshot must not orphan the chain.
    arena.rewind(snap);
    try testing.expectEqual(cap, arena.queryCapacity());
    try testing.expect(arena.current == arena.first);

    // The retained chunks are reused, not re-allocated.
    _ = try a.alloc(u8, 1024);
    try testing.expectEqual(cap, arena.queryCapacity());
}

pub fn IndexedMemoryPool(comptime Item: type) type {
    // Heavily inspired by std.heap.MemoryPool

    return struct {
        const Self = @This();
        pub const no_next_free: usize = std.math.maxInt(usize);
        pub const empty: Self = .{ .items = &.{} };

        // Make sure we have enough space for a usize.
        const node_align = std.mem.Alignment.of(usize).max(.of(Item));
        /// Designed to use items directly. May move locations after calling `.create()`.
        items: []align(node_align.toByteUnits()) Item,
        /// If == no_next_free, it doesn't point to anything
        next_free: usize = no_next_free,
        /// `len` is the largest index used, while `items.len` is the capacity.
        len: usize = 0,
        /// `count` is how many items are live.
        count: usize = 0,

        /// Capacity must be > 0
        pub fn initWithCapacity(gpa: Allocator, capacity: usize) !Self {
            if (capacity == 0) @panic("Capacity must be larger than 0");
            return .{ .items = try gpa.alloc(Item, capacity) };
        }

        pub fn create(self: *Self, gpa: Allocator) !usize {
            // Resize/realloc if needed
            const new_size = @max(self.items.len, 4) * 2;
            if (self.len >= self.items.len) {
                self.items = try gpa.realloc(self.items, new_size);
            }

            return self.createAssumeCapacity();
        }

        pub fn createAssumeCapacity(self: *Self) usize {
            self.count += 1;
            errdefer self.count -= 1;

            // Check if there's anything on the free list.
            if (self.next_free != no_next_free) {
                const next_free = self.next_free;
                // follow to next free
                const item_ptr: *Item = &self.items[next_free];
                const int_ptr: *usize = @ptrCast(item_ptr);
                self.next_free = int_ptr.*;
                return next_free;
            }

            assert(self.len < self.items.len);

            const new_index = self.len;
            self.len += 1;
            assert(new_index != no_next_free);
            return new_index;
        }

        /// Resets the pool to empty while keeping the backing memory allocated.
        pub fn clearRetainingCapacity(self: *Self) void {
            self.next_free = no_next_free;
            self.len = 0;
            self.count = 0;
        }

        pub fn destroy(self: *Self, index: usize) void {
            self.count -= 1;

            self.items[index] = undefined;
            const item_ptr: *Item = &self.items[index];
            const int_ptr: *usize = @ptrCast(item_ptr);
            int_ptr.* = self.next_free;
            self.next_free = index;
        }

        pub fn deinit(self: *Self, gpa: Allocator) void {
            gpa.free(self.items);
        }

        /// For debugging purposes only. Dumps everything that was leaked.
        pub fn dumpLeaked(self: *Self, scratch: Allocator, comptime fmt: []const u8) !void {
            // We'll go through the free list, adding each free item to the `not_leaked` set.
            var not_leaked = std.AutoHashMap(usize, void).init(scratch);
            defer not_leaked.deinit();

            var next_free = self.next_free;
            while (next_free != no_next_free) {
                try not_leaked.put(next_free, undefined);

                const item_ptr: *Item = &self.items[next_free];
                const int_ptr: *usize = @ptrCast(item_ptr);

                next_free = int_ptr.*;
            }

            for (0..self.len) |i| {
                if (!not_leaked.contains(i)) {
                    std.debug.print(fmt, .{ i, self.items[i] });
                }
            }
        }
    };
}

test "indexed memory pool" {
    const ta = testing.allocator;

    const TestStruct = struct {
        a: u64,
        b: u64,
    };

    const Pool = IndexedMemoryPool(TestStruct);

    // Make sure values are created and freed in the correct order
    var pool = try Pool.initWithCapacity(ta, 1);
    defer pool.deinit(ta);
    try testing.expectEqual(0, pool.create(ta));
    try testing.expectEqual(1, pool.create(ta));
    try testing.expectEqual(2, pool.create(ta));
    pool.destroy(1);
    pool.destroy(0);
    try testing.expectEqual(0, pool.create(ta));
    try testing.expectEqual(1, pool.create(ta));
}

pub fn expectErrorOrOom(expected_error: anyerror, actual_error_union: anytype) !void {
    if (actual_error_union) |_| {} else |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        else => {},
    }

    try testing.expectError(expected_error, actual_error_union);
}

/// Context is a standard hash map context
pub fn LruCache(comptime K: type, comptime V: type, comptime Context: type) type {
    return struct {
        const Self = @This();

        pub const Node = struct {
            prev: ?u32,
            next: ?u32,
            key: K,
            item: V,
        };

        pool: IndexedMemoryPool(Node),
        mapping: std.HashMapUnmanaged(K, u32, Context, 80),
        max_size: u32,
        last: ?u32 = null,
        first: ?u32 = null,

        pub fn initWithCapacity(gpa: Allocator, max_size: u32) !Self {
            var new_lru: Self = .{
                .pool = try .initWithCapacity(gpa, max_size),
                .mapping = .{},
                .max_size = max_size,
                .last = null,
                .first = null,
            };
            errdefer new_lru.pool.deinit(gpa);

            try new_lru.mapping.ensureTotalCapacity(gpa, max_size);

            return new_lru;
        }

        pub fn deinit(self: *Self, gpa: Allocator) void {
            self.mapping.deinit(gpa);
            self.pool.deinit(gpa);
        }

        fn moveToFirst(self: *Self, index: u32) void {
            const nodes = self.pool.items;
            const node = &nodes[index];

            // Already the first item?
            if (self.first == index) return;

            // Unlink the item.
            if (node.prev) |prev| nodes[prev].next = node.next;
            if (node.next) |next| nodes[next].prev = node.prev;

            // If it was the last, update the last.
            if (index == self.last) self.last = node.prev;

            // Move to first item.
            node.prev = null;
            node.next = self.first;
            if (self.first) |first| nodes[first].prev = index;
            self.first = index;
        }

        pub const ValueIterator = struct {
            nodes: []Node,
            current: ?u32,

            pub fn next(self: *ValueIterator) ?*V {
                const index = self.current orelse return null;
                const node = &self.nodes[index];
                self.current = node.next;
                return &node.item;
            }
        };

        /// Iterates over all values in LRU order (most recently used first).
        pub fn valueIterator(self: *Self) ValueIterator {
            return .{
                .nodes = self.pool.items,
                .current = self.first,
            };
        }

        /// Removes all entries but keeps the underlying capacity allocated.
        pub fn clearRetainingCapacity(self: *Self) void {
            self.mapping.clearRetainingCapacity();
            self.pool.clearRetainingCapacity();
            self.first = null;
            self.last = null;
        }

        pub fn getPtr(self: *Self, key: K) ?*V {
            const value = self.mapping.get(key);

            if (value) |val_index| {
                self.moveToFirst(val_index);
                return &self.pool.items[val_index].item;
            } else return null;
        }

        pub fn get(self: *Self, key: K) ?V {
            return if (self.getPtr(key)) |ptr| ptr.* else null;
        }

        /// Returns an old value if it was evicted.
        pub fn put(self: *Self, key: K, value: V) ?V {
            // Check if this key already exists.
            if (self.mapping.get(key)) |val_index| {
                self.moveToFirst(val_index);
                // Save the old value so we can return it to the caller.
                const old_value = self.pool.items[val_index].item;
                // Update in place.
                self.pool.items[val_index].item = value;

                return old_value;
            } else {
                // Doesn't exist, so we need to create it.
                var last_value: ?V = null;

                // Evict the last used item if we've reached `max_size`.
                const new: u32 = blk: {
                    if (self.pool.count >= self.max_size) {
                        const last_index = self.last.?;
                        const last = &self.pool.items[last_index];

                        assert(self.mapping.remove(last.key));
                        self.last = last.prev;
                        if (self.last) |new_last| {
                            self.pool.items[new_last].next = null;
                        }
                        last_value = last.item;
                        last.* = undefined;
                        // No need to destroy the item, since we'll reuse it.
                        break :blk last_index;
                    } else {
                        break :blk @intCast(self.pool.createAssumeCapacity());
                    }
                };

                self.pool.items[new] = .{
                    .prev = null,
                    .next = self.first,
                    .key = key,
                    .item = value,
                };

                // Link the new item in.
                if (self.first) |first| {
                    self.pool.items[first].prev = new;
                    self.first = new;
                } else {
                    self.first = new;
                    self.last = new;
                }

                self.mapping.putAssumeCapacity(key, new);

                return last_value;
            }
        }
    };
}

const StringCache = LruCache([]const u8, []const u8, struct {
    pub fn hash(self: @This(), s: []const u8) u64 {
        _ = self;
        return std.hash.Wyhash.hash(0, s);
    }

    pub fn eql(self: @This(), a: []const u8, b: []const u8) bool {
        _ = self;
        return mem.eql(u8, a, b);
    }
});

test "lru cache" {
    // Basic put and get.
    {
        var cache: StringCache = try .initWithCapacity(testing.allocator, 3);
        defer cache.deinit(testing.allocator);

        try testing.expectEqual(null, cache.put("key1", "value1"));
        try testing.expectEqualStrings("value1", cache.get("key1").?);
        try testing.expectEqual(null, cache.put("key2", "value2"));
        try testing.expectEqual(null, cache.put("key3", "value3"));
        try testing.expectEqual(cache.put("key4", "value4"), "value1");
        try testing.expectEqual(null, cache.get("key1"));
    }

    // Check that get promotes key, saving it from eviction.
    {
        var cache: StringCache = try .initWithCapacity(testing.allocator, 2);
        defer cache.deinit(testing.allocator);

        // Fill cache, then promote key1 by accessing it.
        try testing.expectEqual(null, cache.put("key1", "value1"));
        try testing.expectEqual(null, cache.put("key2", "value2"));
        try testing.expectEqualStrings("value1", cache.get("key1").?);

        // key2 should be evicted, not key1.
        try testing.expectEqualStrings("value2", cache.put("key3", "value3").?);
        try testing.expectEqualStrings("value1", cache.get("key1").?);
        try testing.expectEqual(null, cache.get("key2"));
    }

    // Check that updating existing key returns old value without evicting.
    {
        var cache: StringCache = try .initWithCapacity(testing.allocator, 2);
        defer cache.deinit(testing.allocator);

        // Fill cache, then update key1 in place.
        try testing.expectEqual(null, cache.put("key1", "old"));
        try testing.expectEqual(null, cache.put("key2", "value2"));
        try testing.expectEqualStrings("old", cache.put("key1", "new").?);

        // Both keys should still be present.
        try testing.expectEqualStrings("new", cache.get("key1").?);
        try testing.expectEqualStrings("value2", cache.get("key2").?);
    }

    // Check re-inserting an evicted key.
    {
        var cache: StringCache = try .initWithCapacity(testing.allocator, 2);
        defer cache.deinit(testing.allocator);

        // Evict key1, then re-insert it — evicts key2 (now LRU).
        try testing.expectEqual(null, cache.put("key1", "value1"));
        try testing.expectEqual(null, cache.put("key2", "value2"));
        try testing.expectEqualStrings("value1", cache.put("key3", "value3").?);
        try testing.expectEqualStrings("value2", cache.put("key1", "value1-new").?);

        // key1 and key3 remain; key2 was evicted.
        try testing.expectEqualStrings("value1-new", cache.get("key1").?);
        try testing.expectEqualStrings("value3", cache.get("key3").?);
        try testing.expectEqual(null, cache.get("key2"));
    }
}

/// Node = struct, Edge = pointer + field name.
pub const StructIterator = struct {
    ptr: *anyopaque,
    vtable: *const VTable,
    arena: std.mem.Allocator,

    pub const Error = std.mem.Allocator.Error;

    pub const NodeInfo = struct {
        parent_info: ?*const NodeInfo,
        node: *const anyopaque,
        enumerate_struct: ?*const EnumerateStructFn,
        type_name: []const u8,
        as_string: ?[]const u8,
        /// Whether we created this node on the arena instead of pulling it from the heap.
        is_synthetic: bool = false,
    };

    pub const EnumerateStructFn = fn (ctx: StructIterator, node_info: *const NodeInfo) Error!void;
    pub const VTable = struct {
        visit_node: *const fn (ctx: StructIterator, node_info: *const NodeInfo, edge_coming_from: ?[]const u8) Error!void,
    };

    fn getEnumerateStruct(T: type) ?*const EnumerateStructFn {
        switch (@typeInfo(T)) {
            .@"struct", .@"enum", .@"union", .@"opaque" => {
                return if (@hasDecl(T, "enumerateStruct")) &T.enumerateStruct else null;
            },
            else => return null,
        }
    }

    pub fn followUnparentedNode(ctx: StructIterator, T: type, ptr: *const T) Error!void {
        const node_info: NodeInfo = .{
            .parent_info = null,
            .node = ptr,
            .enumerate_struct = getEnumerateStruct(T),
            .type_name = @typeName(T),
            .as_string = null,
        };
        try ctx.vtable.visit_node(ctx, &node_info, null);
    }

    pub fn followNode(
        ctx: StructIterator,
        T: type,
        node_info: *const NodeInfo,
        edge_coming_from: []const u8,
        node_ptr: *const T,
    ) Error!void {
        const child_node: NodeInfo = .{
            .parent_info = node_info,
            .node = node_ptr,
            .enumerate_struct = getEnumerateStruct(T),
            .type_name = @typeName(T),
            .as_string = null,
        };
        try ctx.vtable.visit_node(ctx, &child_node, edge_coming_from);
    }

    pub fn addFieldString(
        ctx: StructIterator,
        T: type,
        node_info: *const NodeInfo,
        edge_coming_from: []const u8,
        val: []const u8,
    ) Error!void {
        const dummy_node = try ctx.arena.create(u8);
        const child_node: NodeInfo = .{
            .parent_info = node_info,
            .node = dummy_node,
            .enumerate_struct = null,
            .type_name = @typeName(T),
            .as_string = try ctx.arena.dupeSentinel(u8, val, 0),
            .is_synthetic = true,
        };
        try ctx.vtable.visit_node(ctx, &child_node, edge_coming_from);
    }

    pub fn addField(
        ctx: StructIterator,
        T: type,
        node_info: *const NodeInfo,
        edge_coming_from: []const u8,
        comptime fmt: []const u8,
        val: T,
    ) Error!void {
        const dummy_node = try ctx.arena.create(u8);
        const child_node: NodeInfo = .{
            .parent_info = node_info,
            .node = dummy_node,
            .enumerate_struct = null,
            .type_name = @typeName(T),
            .as_string = try std.fmt.allocPrint(ctx.arena, fmt, .{val}),
            .is_synthetic = true,
        };
        try ctx.vtable.visit_node(ctx, &child_node, edge_coming_from);
    }
};

pub const GraphWalker = struct {
    pub const Edge = struct {
        from: *const anyopaque,
        to: *const anyopaque,
        field_name: []const u8,
    };
    pub const Node = struct {
        type_name: []const u8,
        as_string: ?[]const u8,
        is_synthetic: bool,
    };

    nodes: std.AutoHashMapUnmanaged(*const anyopaque, Node),
    edges: std.ArrayList(Edge),

    pub const empty: GraphWalker = .{ .nodes = .empty, .edges = .empty };
    pub const vtable: StructIterator.VTable = .{ .visit_node = visitNode };

    pub fn promote(self: *GraphWalker, arena: std.mem.Allocator) StructIterator {
        return .{
            .ptr = self,
            .vtable = &vtable,
            .arena = arena,
        };
    }

    fn visitNode(
        ctx: StructIterator,
        info: *const StructIterator.NodeInfo,
        edge_coming_from: ?[]const u8,
    ) StructIterator.Error!void {
        const self: *GraphWalker = @ptrCast(@alignCast(ctx.ptr));
        if (info.parent_info) |parent_info| {
            try self.edges.append(ctx.arena, .{
                .from = parent_info.node,
                .to = info.node,
                .field_name = edge_coming_from.?,
            });
        }
        if (self.nodes.contains(info.node)) return; // Avoid double counting and cycles.
        try self.nodes.put(ctx.arena, info.node, .{
            .type_name = info.type_name,
            .as_string = info.as_string,
            .is_synthetic = info.is_synthetic,
        });
        if (info.enumerate_struct) |follow_fn| try follow_fn(ctx, info);
    }
};

const StructIteratorTest = struct {
    const NodeInfo = StructIterator.NodeInfo;
    pub const Bar = struct {};

    /// A node with up to two named children (`a`, `b`) for exercising cycles,
    /// diamonds, and the two-child case. `name` is for human inspection only.
    pub const Node = struct {
        name: []const u8,
        a: ?*const Node = null,
        b: ?*const Node = null,

        pub fn enumerateStruct(ctx: StructIterator, node_info: *const NodeInfo) StructIterator.Error!void {
            const self: *const Node = @ptrCast(@alignCast(node_info.node));
            if (self.a) |child| try ctx.followNode(Node, node_info, "a", child);
            if (self.b) |child| try ctx.followNode(Node, node_info, "b", child);
        }
    };
};

test "GraphWalker: single edge records both endpoints" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var walker = GraphWalker.empty;
    const iter = walker.promote(arena.allocator());
    var bar: StructIteratorTest.Node = .{ .name = "bar" };
    var foo: StructIteratorTest.Node = .{ .name = "foo", .a = &bar };
    try iter.followUnparentedNode(StructIteratorTest.Node, &foo);

    try std.testing.expectEqual(@as(usize, 2), walker.nodes.count());
    try std.testing.expect(walker.nodes.contains(@ptrCast(&foo)));
    try std.testing.expect(walker.nodes.contains(@ptrCast(&bar)));
    try std.testing.expectEqual(@as(usize, 1), walker.edges.items.len);
    const edge = walker.edges.items[0];
    try std.testing.expectEqual(@as(*const anyopaque, @ptrCast(&foo)), edge.from);
    try std.testing.expectEqual(@as(*const anyopaque, @ptrCast(&bar)), edge.to);
    try std.testing.expectEqualStrings("a", edge.field_name);
}

test "GraphWalker: two children both recorded" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var walker = GraphWalker.empty;
    const iter = walker.promote(arena.allocator());
    var b: StructIteratorTest.Node = .{ .name = "b" };
    var c: StructIteratorTest.Node = .{ .name = "c" };
    var a: StructIteratorTest.Node = .{ .name = "a", .a = &b, .b = &c };
    try iter.followUnparentedNode(StructIteratorTest.Node, &a);

    try std.testing.expectEqual(@as(usize, 3), walker.nodes.count());
    try std.testing.expectEqual(@as(usize, 2), walker.edges.items.len);
}

test "GraphWalker: cycle records back-edge without recursing" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var walker = GraphWalker.empty;
    const iter = walker.promote(arena.allocator());
    var a: StructIteratorTest.Node = .{ .name = "a" };
    var b: StructIteratorTest.Node = .{ .name = "b" };
    a.a = &b;
    b.a = &a; // back-edge: a -> b -> a
    try iter.followUnparentedNode(StructIteratorTest.Node, &a);

    // Exactly two nodes visited -- the back-edge did not re-enter a.
    try std.testing.expectEqual(@as(usize, 2), walker.nodes.count());
    // Both directions recorded, because edges are recorded before the
    // visited check gates recursion.
    try std.testing.expectEqual(@as(usize, 2), walker.edges.items.len);
}

test "GraphWalker: diamond records both edges into shared child" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var walker = GraphWalker.empty;
    const iter = walker.promote(arena.allocator());
    var d: StructIteratorTest.Node = .{ .name = "d" };
    var b: StructIteratorTest.Node = .{ .name = "b", .a = &d };
    var c: StructIteratorTest.Node = .{ .name = "c", .a = &d };
    var a: StructIteratorTest.Node = .{ .name = "a", .a = &b, .b = &c };
    try iter.followUnparentedNode(StructIteratorTest.Node, &a);

    // d is visited once, but both edges into it are recorded.
    try std.testing.expectEqual(@as(usize, 4), walker.nodes.count());
    try std.testing.expectEqual(@as(usize, 4), walker.edges.items.len);
}

test "GraphWalker: leaf root recorded with no edges" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var walker = GraphWalker.empty;
    const iter = walker.promote(arena.allocator());
    var leaf: StructIteratorTest.Node = .{ .name = "leaf" };
    try iter.followUnparentedNode(StructIteratorTest.Node, &leaf);

    try std.testing.expectEqual(@as(usize, 1), walker.nodes.count());
    try std.testing.expect(walker.nodes.contains(@ptrCast(&leaf)));
    try std.testing.expectEqual(@as(usize, 0), walker.edges.items.len);
}
